name: 'AWS Lambda Layer Release - ktx-mega'
author: Gaurav Sharma <sharma02gaurav@gmail.com>
description: 'Action lets you release your latest lambda layer version'
inputs:
  access_key_id:  # id of input
    description: 'AWS_ACCESS_KEY_ID. String'
    required: true
  secret_access_key:
    description: 'AWS_SECRET_ACCESS_KEY. String'
    required: true
  layer_name:
    description: "AWS lambda layer name. String"
    required: true
  archive:
    description: "Path to lambda layer zip archive. String"
    required: true
  region:
    description: "The AWS region for this lambda and layer. Defaults to ap-south-1 (Mumbai). String"
    required: true
    default: "ap-south-1"
  runtimes:
    description: 'List of runtimes. "nodejs" || "nodejs4.3" || "nodejs6.10" || "nodejs8.10" || "nodejs10.x" || "nodejs12.x" || "nodejs14.x" || "nodejs16.x" || "java8" || "java8.al2" || "java11" || "python2.7" || "python3.6" || "python3.7" || "python3.8" || "python3.9" || "dotnetcore1.0" || "dotnetcore2.0" || "dotnetcore2.1" || "dotnetcore3.1" || "dotnet6" || "nodejs4.3-edge" || "go1.x" || "ruby2.5" || "ruby2.7" || "provided" || "provided.al2" || "nodejs18.x" || "python3.10" || "java17" || "ruby3.2" || "python3.11". String[]'
    required: false
  architectures:
    description: 'List of architectures. "x86_64" || "arm64". String[]'
    required: false
    default: '["x86_64", "arm64"]'
  s3_bucket:
    description: 's3 bucket is required if layer exceeds 10MB size. String'
    required: false
  functions:
    description: "Optional Lambda function name(s) to update the layer to latest. String[]"
    required: false
    default: '[]'
  auto_update:
    description: "Optional Automatically update all Lambda functions using the layer to the latest layer version. Boolean"
    required: false
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
